**EZEALAJI LUCKY DAMIAN**

**SOLUTIONS TO ASSIGNMENT ONE**

**QUESTION ONE**

In [1]:

def weekly_overtime_pay():
    standard_work_hours = 40
    regular_hourly_pay = 45
    over_time_pay_rate = 50
    total_hour_worked = float(input("Enter the total number of hours you worked in the week:"))
    base_pay = standard_work_hours * regular_hourly_pay
    over_time_hours = total_hour_worked - standard_work_hours
    over_time_pay = over_time_hours * over_time_pay_rate
    gross_pay = base_pay + over_time_pay
    if total_hour_worked < standard_work_hours:
        print("Standard number of weekly work hours: " "{}hrs".format(standard_work_hours))
        print("Total number of hours worked: " "{}hrs".format(total_hour_worked))
        print("You worked less than the required number of hours this week.")
        print("Your pay this week is: " + "$" + str(total_hour_worked * regular_hourly_pay))
    elif total_hour_worked > standard_work_hours:
        print("Standard number of weekly work hours: " "{}hrs".format(standard_work_hours))
        print("Total number of hours worked: " "{}hrs".format(total_hour_worked))
        print("This week you have an overtime of: " "{}hrs.".format(over_time_hours),\
            "Your pay this week is: " "${}.".format(gross_pay))
    else:
        print("Standard number of weekly work hours: " "{}hrs".format(standard_work_hours))
        print("Total number of hours worked: " "{}hrs".format(total_hour_worked))
        print("You do not have an overtime this week.",\
            "Your pay this week is: " "${}.".format(base_pay)) 

In [2]:
weekly_overtime_pay()

Enter the total number of hours you worked in the week: 65


Standard number of weekly work hours: 40hrs
Total number of hours worked: 65.0hrs
This week you have an overtime of: 25.0hrs. Your pay this week is: $3050.0.


**QUESTION TWO**

In [3]:
# Requesting user to input 10 float values which is stored in a variable.

mylist1 = []
m = 10
for num in range(m):
    fig = float(input("Enter a float value"))
    mylist1.append(fig)
print(mylist1)

Enter a float value 23.5
Enter a float value 14.8
Enter a float value 65.4
Enter a float value 74.3
Enter a float value 7
Enter a float value 2
Enter a float value 6
Enter a float value 98.6
Enter a float value 60.5
Enter a float value 100.4


[23.5, 14.8, 65.4, 74.3, 7.0, 2.0, 6.0, 98.6, 60.5, 100.4]


In [4]:
# List comprehension of mylist1

mylist2 = [mylist1 for item in range(1)]
print(mylist2)

[[23.5, 14.8, 65.4, 74.3, 7.0, 2.0, 6.0, 98.6, 60.5, 100.4]]


In [5]:
mylist3 = mylist2[0]

In [6]:
# Sorting of mylist3

mylist3

[23.5, 14.8, 65.4, 74.3, 7.0, 2.0, 6.0, 98.6, 60.5, 100.4]

In [7]:
mylist3.sort()

In [8]:
mylist3

[2.0, 6.0, 7.0, 14.8, 23.5, 60.5, 65.4, 74.3, 98.6, 100.4]

**QUESTION THREE**


In [9]:
# Write a program that creates a single dictionary containing the following key-value pairs

mydict1 = {"School":"MTSU", "Textbooks":14, "Level":"Elementary", "Hobby":"Dancing", "Height":"4.5 inch", "Food":"Amala"}

In [10]:
mydict1

{'School': 'MTSU',
 'Textbooks': 14,
 'Level': 'Elementary',
 'Hobby': 'Dancing',
 'Height': '4.5 inch',
 'Food': 'Amala'}

In [11]:
# Update the dictionary with your credentials

mydict1.update({"School":"Nnamdi Azikiwe University, Awka","Textbooks":10,"Level":"Masters","Hobby":"Coding","Height":"5.2 inch","Food":"Fried rice and chicken"})

In [12]:
mydict1

{'School': 'Nnamdi Azikiwe University, Awka',
 'Textbooks': 10,
 'Level': 'Masters',
 'Hobby': 'Coding',
 'Height': '5.2 inch',
 'Food': 'Fried rice and chicken'}

In [13]:
# Add new key-value pairs

mydict1["Is_location_USA"] = "True"

In [14]:
mydict1

{'School': 'Nnamdi Azikiwe University, Awka',
 'Textbooks': 10,
 'Level': 'Masters',
 'Hobby': 'Coding',
 'Height': '5.2 inch',
 'Food': 'Fried rice and chicken',
 'Is_location_USA': 'True'}

In [15]:
mydict1["Is_graduated"] = "No"

In [16]:
mydict1

{'School': 'Nnamdi Azikiwe University, Awka',
 'Textbooks': 10,
 'Level': 'Masters',
 'Hobby': 'Coding',
 'Height': '5.2 inch',
 'Food': 'Fried rice and chicken',
 'Is_location_USA': 'True',
 'Is_graduated': 'No'}

In [17]:
# Remove the key-value pair Hobby:Dancing

mydict1.pop("Hobby")

'Coding'

In [18]:
mydict1

{'School': 'Nnamdi Azikiwe University, Awka',
 'Textbooks': 10,
 'Level': 'Masters',
 'Height': '5.2 inch',
 'Food': 'Fried rice and chicken',
 'Is_location_USA': 'True',
 'Is_graduated': 'No'}

In [19]:
# Delete last entry of the updated dictionary

mydict1.popitem()

('Is_graduated', 'No')

In [20]:
mydict1

{'School': 'Nnamdi Azikiwe University, Awka',
 'Textbooks': 10,
 'Level': 'Masters',
 'Height': '5.2 inch',
 'Food': 'Fried rice and chicken',
 'Is_location_USA': 'True'}

**QUESTION FOUR**

In [21]:
import numpy as np

In [22]:
# Create an Array of ones of size 20 by 11 called myarray1

myarray1 = np.ones((20,11),dtype = float)

In [23]:
myarray1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

In [24]:
# Multiply scalar of 0.5 by the array

myarray1 = myarray1 * 0.5

In [25]:
myarray1

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.

In [26]:
# Update the 6th row with a value of 10.5

myarray1[5] = 10.5

In [27]:
myarray1

array([[ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,

In [28]:
# Update the 7th row with a value of 11.5

myarray1[6] = 11.5

In [29]:
myarray1

array([[ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,

In [30]:
# Update the 1st column with a value of 9.5

myarray1[:,0] = 9.5

In [31]:
myarray1

array([[ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [ 9.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,

In [32]:
# Slice the 5th row to the 11st row in myarray1

myarray1[4:11,:]

array([[ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5, 10.5],
       [ 9.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5, 11.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5],
       [ 9.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5]])

In [33]:
# Slice the 6th column to 9th column in myarray1

myarray1[:,5:9]

array([[ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [10.5, 10.5, 10.5, 10.5],
       [11.5, 11.5, 11.5, 11.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5,  0.5]])

In [34]:
# Merge the 6th column with the 8th column using np.hstack

myarray1_col6 = myarray1[:,5]

In [35]:
myarray1_col6

array([ 0.5,  0.5,  0.5,  0.5,  0.5, 10.5, 11.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5])

In [36]:
myarray1_col6 = myarray1_col6.reshape(-1,1)

In [37]:
myarray1_col6

array([[ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [10.5],
       [11.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5]])

In [38]:
myarray1_col8 = myarray1[:,8]

In [39]:
myarray1_col8

array([ 0.5,  0.5,  0.5,  0.5,  0.5, 10.5, 11.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5])

In [40]:
myarray1_col8 = myarray1_col8.reshape(-1,1)

In [41]:
myarray1_col8

array([[ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [10.5],
       [11.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5]])

In [42]:
myarray1_hstack = np.hstack((myarray1_col6,myarray1_col8))

In [43]:
myarray1_hstack

array([[ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [10.5, 10.5],
       [11.5, 11.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5,  0.5]])

In [44]:
# Merge the 5th column with the 10th column using np.vstack

myarray1_col5 = myarray1[:,4]

In [45]:
myarray1_col5

array([ 0.5,  0.5,  0.5,  0.5,  0.5, 10.5, 11.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5])

In [46]:
myarray1_col5 = myarray1_col5.reshape(-1,1)

In [47]:
myarray1_col5

array([[ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [10.5],
       [11.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5]])

In [48]:
myarray1_col10 = myarray1[:,9]

In [49]:
myarray1_col10

array([ 0.5,  0.5,  0.5,  0.5,  0.5, 10.5, 11.5,  0.5,  0.5,  0.5,  0.5,
        0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5])

In [50]:
myarray1_col10 = myarray1_col10.reshape(-1,1)

In [51]:
myarray1_col10

array([[ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [10.5],
       [11.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5]])

In [52]:
myarray1_vstack = np.vstack((myarray1_col5,myarray1_col10))

In [53]:
myarray1_vstack

array([[ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [10.5],
       [11.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [10.5],
       [11.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5],
       [ 0.5]])